name: sachkundenachweis
description: Vorbereitung auf den Sachkundenachweis nach LHundG NRW
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Lokale Speicherung
  shared_preferences: ^2.2.2

  # Fortschrittsanzeige
  fl_chart: ^1.0.0

  # (optional: für zusätzliche Icons)
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
